-- Snowflake Views for Power BI GitHub Dashboard

USE DATABASE GITSTAR_DB;
USE SCHEMA PUBLIC;

-- 1. Dashboard Repository Summary View
CREATE OR REPLACE VIEW DASHBOARD_REPO_SUMMARY AS
SELECT 
    r.ID AS REPO_ID,
    r.NAME AS REPO_NAME,
    l.NAME AS LANGUAGE,
    r.STARGAZERS_COUNT,
    r.FORKS_COUNT,
    u.LOGIN AS OWNER_LOGIN,
    u.NAME AS OWNER_NAME,
    ut.TYPE_NAME AS OWNER_TYPE,
    r.CREATED_AT,
    r.UPDATED_AT
FROM REPOSITORIES r
JOIN LANGUAGES l ON r.LANGUAGE_ID = l.ID
JOIN USERS u ON r.OWNER_ID = u.ID
JOIN USER_TYPES ut ON u.TYPE_ID = ut.ID;

-- 2. Dashboard Commit Trends View
CREATE OR REPLACE VIEW DASHBOARD_COMMIT_TRENDS AS
SELECT 
    c.SHA,
    c.REPOSITORY_ID,
    r.NAME AS REPO_NAME,
    c.AUTHOR_ID,
    a.NAME AS AUTHOR_NAME,
    c.COMMIT_DATE,
    DATE(c.COMMIT_DATE) AS COMMIT_DAY,
    HOUR(c.COMMIT_DATE) AS COMMIT_HOUR,
    DAYNAME(c.COMMIT_DATE) AS COMMIT_DAY_OF_WEEK
FROM COMMITS c
JOIN REPOSITORIES r ON c.REPOSITORY_ID = r.ID
JOIN AUTHORS a ON c.AUTHOR_ID = a.ID;

-- 3. Dashboard PR Insights View
CREATE OR REPLACE VIEW DASHBOARD_PR_INSIGHTS AS
SELECT 
    p.PR_ID,
    r.NAME AS REPO_NAME,
    p.PR_NUMBER,
    p.TITLE,
    p.STATE,
    p.AUTHOR_LOGIN,
    p.CREATED_AT,
    p.MERGED_AT,
    DATEDIFF('day', p.CREATED_AT, COALESCE(p.MERGED_AT, CURRENT_TIMESTAMP())) AS DAYS_TO_MERGE
FROM PULL_REQUESTS p
JOIN REPOSITORIES r ON p.REPOSITORY_ID = r.ID;
