-- SQLite DDL for GitHub Normalized Schema

-- 1. Create User Types Table
CREATE TABLE USER_TYPES (
    ID INTEGER PRIMARY KEY,
    TYPE_NAME TEXT
);

-- 2. Create Users Table
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY,
    LOGIN TEXT,
    NAME TEXT,
    TYPE_ID INTEGER,
    PUBLIC_REPOS INTEGER,
    FOLLOWERS INTEGER,
    FOLLOWING INTEGER,
    CREATED_AT TEXT,
    FOREIGN KEY (TYPE_ID) REFERENCES USER_TYPES(ID)
);

-- 3. Create Languages Table
CREATE TABLE LANGUAGES (
    ID INTEGER PRIMARY KEY,
    NAME TEXT
);

-- 4. Create Repositories Table
CREATE TABLE REPOSITORIES (
    ID INTEGER PRIMARY KEY,
    NAME TEXT,
    LANGUAGE_ID INTEGER,
    STARGAZERS_COUNT INTEGER,
    FORKS_COUNT INTEGER,
    CREATED_AT TEXT,
    UPDATED_AT TEXT,
    OWNER_ID INTEGER,
    FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGES(ID),
    FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
);

-- 5. Create Authors Table
CREATE TABLE AUTHORS (
    ID INTEGER PRIMARY KEY,
    NAME TEXT
);

-- 6. Create Commits Table
CREATE TABLE COMMITS (
    SHA TEXT,
    REPOSITORY_ID INTEGER,
    AUTHOR_ID INTEGER,
    COMMIT_DATE TEXT,
    PRIMARY KEY (SHA, REPOSITORY_ID),
    FOREIGN KEY (REPOSITORY_ID) REFERENCES REPOSITORIES(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

-- 7. Create Pull Requests Table
CREATE TABLE PULL_REQUESTS (
    PR_ID INTEGER PRIMARY KEY,
    REPOSITORY_ID INTEGER,
    PR_NUMBER INTEGER,
    TITLE TEXT,
    STATE TEXT,
    AUTHOR_LOGIN TEXT,
    CREATED_AT TEXT,
    MERGED_AT TEXT,
    FOREIGN KEY (REPOSITORY_ID) REFERENCES REPOSITORIES(ID)
);
