-- Snowflake DDL for GitHub Normalized Schema

-- 1. Create User Types Table
CREATE OR REPLACE TABLE USER_TYPES (
    ID INTEGER PRIMARY KEY,
    TYPE_NAME STRING
);

-- 2. Create Users Table
CREATE OR REPLACE TABLE USERS (
    ID INTEGER PRIMARY KEY,
    LOGIN STRING,
    NAME STRING,
    TYPE_ID INTEGER,
    PUBLIC_REPOS INTEGER,
    FOLLOWERS INTEGER,
    FOLLOWING INTEGER,
    CREATED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (TYPE_ID) REFERENCES USER_TYPES(ID)
);

-- 3. Create Languages Table
CREATE OR REPLACE TABLE LANGUAGES (
    ID INTEGER PRIMARY KEY,
    NAME STRING
);

-- 4. Create Repositories Table
CREATE OR REPLACE TABLE REPOSITORIES (
    ID INTEGER PRIMARY KEY,
    NAME STRING,
    LANGUAGE_ID INTEGER,
    STARGAZERS_COUNT INTEGER,
    FORKS_COUNT INTEGER,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    OWNER_ID INTEGER,
    FOREIGN KEY (LANGUAGE_ID) REFERENCES LANGUAGES(ID),
    FOREIGN KEY (OWNER_ID) REFERENCES USERS(ID)
);

-- 5. Create Authors Table
CREATE OR REPLACE TABLE AUTHORS (
    ID INTEGER PRIMARY KEY,
    NAME STRING
);

-- 6. Create Commits Table
CREATE OR REPLACE TABLE COMMITS (
    SHA STRING PRIMARY KEY,
    REPOSITORY_ID INTEGER,
    AUTHOR_ID INTEGER,
    COMMIT_DATE TIMESTAMP_NTZ,
    FOREIGN KEY (REPOSITORY_ID) REFERENCES REPOSITORIES(ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID)
);

-- 7. Create Pull Requests Table
CREATE OR REPLACE TABLE PULL_REQUESTS (
    PR_ID INTEGER PRIMARY KEY,
    REPOSITORY_ID INTEGER,
    PR_NUMBER INTEGER,
    TITLE STRING,
    STATE STRING,
    AUTHOR_LOGIN STRING,
    CREATED_AT TIMESTAMP_NTZ,
    MERGED_AT TIMESTAMP_NTZ,
    FOREIGN KEY (REPOSITORY_ID) REFERENCES REPOSITORIES(ID)
);


